// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlhJngSyzaxOQDqEPMxZi_kcMQPhr97Dw',
    appId: '1:354377928899:web:f756ab0a4268d8998e5276',
    messagingSenderId: '354377928899',
    projectId: 'financial-control-app-affe8',
    authDomain: 'financial-control-app-affe8.firebaseapp.com',
    storageBucket: 'financial-control-app-affe8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQC_HOsqTvTzqyt-72eRZxtTxPkE-KdJ4',
    appId: '1:354377928899:android:7710fac34a7d770c8e5276',
    messagingSenderId: '354377928899',
    projectId: 'financial-control-app-affe8',
    storageBucket: 'financial-control-app-affe8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC7ug_HhdHK7Ze5SKgJhmmmiKgX3LWF2s',
    appId: '1:354377928899:ios:cfd4c2a0c03a20b98e5276',
    messagingSenderId: '354377928899',
    projectId: 'financial-control-app-affe8',
    storageBucket: 'financial-control-app-affe8.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC7ug_HhdHK7Ze5SKgJhmmmiKgX3LWF2s',
    appId: '1:354377928899:ios:adcc08a682d6acca8e5276',
    messagingSenderId: '354377928899',
    projectId: 'financial-control-app-affe8',
    storageBucket: 'financial-control-app-affe8.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
